### PR TITLE
CCO-325: Unrevert "CCO-325: add support for workload identity"

### PR DESCRIPTION
**Pull request by bertinatto**
CC @openshift/storage 
/hold
until @openshift/storage-qe  validades the changes

### CODE REVIEW

**Comment by bertinatto** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-azure-sdn-techpreview

**Comment by duanwei33** [comment]
See pre-merge test result in https://issues.redhat.com/browse/STOR-1073.

**Comment by duanwei33** [comment]
Also enabling TechPreviewNoUpgrade will not break the storage CO with the PR.

**Comment by bertinatto** [comment]
> See pre-merge test result in https://issues.redhat.com/browse/STOR-1360.

Thanks a lot, @duanwei33 

/hold cancel

**Comment by bertinatto** [comment]
/hold
until `azure-file-csi-extended` job passes.
/retest-required

**Comment by bertinatto** [comment]
/hold cancel
Removing the hold as the `file-csi-extended` job seems broken. The other 2 Azure File jobs passed.

**Pull request merged**
