### PR TITLE
WIP: Enable fsgroup

### PR DESCRIPTION
**Pull request by bertinatto**

### CODE REVIEW

**Comment by bertinatto** [comment]
We are going to be able to test this properly after the 1.23 rebase lands in o/k (because of the `DelegateFSGroupToCSIDriver` gate, which is enabled by default there).

**Comment by jsafrane** [comment]
/retest
`Cannot create more than 100 public IP addresses for this subscription in this region.`

**Comment by jsafrane** [comment]
fsGroup does not seem to work:

```
fail [k8s.io/kubernetes@v1.23.0/test/e2e/storage/utils/utils.go:728]: Expected
    <string>: 1000
to equal
    <string>: 2000}
```

**Comment by bertinatto** [comment]
Fixed in https://github.com/openshift/azure-file-csi-driver-operator/commit/1273c69a06d121e2706176f12f93381d5704148f

**Pull request closed without merging**
