### PR TITLE
Revert "STOR-1065: Rework sidecar bindings to bind common ClusterRoles"

### PR DESCRIPTION
**Pull request by neisw**
This reverts commit cb05b3b6883fd966a3aaf8bf250309f163ca2374.

Per [OpenShift policy](https://github.com/openshift/enhancements/blob/master/enhancements/release/improving-ci-signal.md#quick-revert), we are reverting this breaking change to get CI and/or nightly payloads flowing again.

[TRT-1158](https://issues.redhat.com/browse/TRT-1158) tracks failures in https://amd64.ocp.releases.ci.openshift.org/releasestream/4.14.0-0.ci/release/4.14.0-0.ci-2023-07-20-162349

Example: https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-azure-sdn-upgrade/1682065697758253056
Show failures for 
[sig-arch] events should not repeat pathologically for ns/openshift-cluster-csi-drivers

Indicating errors such as

`event happened 244 times, something is wrong: ns/openshift-cluster-csi-drivers deployment/azure-file-csi-driver-operator hmsg/7adfb51a41 - pathological/true reason/ClusterRoleBindingUpdateFailed Failed to update ClusterRoleBinding.rbac.authorization.k8s.io/azure-file-csi-attacher-binding: ClusterRoleBinding.rbac.authorization.k8s.io "azure-file-csi-attacher-binding" is invalid: roleRef: Invalid value: rbac.RoleRef{APIGroup:"rbac.authorization.k8s.io", Kind:"ClusterRole", Name:"openshift-csi-main-attacher-role"}: cannot change roleRef From: 19:49:11Z To: 19:49:12Z result=reject `

To unrevert this, revert this PR, and layer an additional separate commit on top that addresses the problem. Before merging the unrevert, please run these jobs on the PR and check the result of (job/X or job/X, test/Y tuple) to confirm the fix has corrected the problem:
/payload 4.14 ci blocking

### CODE REVIEW

**Comment by neisw** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-azure-sdn-upgrade

**Comment by DennisPeriquet** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-azure-sdn-upgrade

**Comment by DennisPeriquet** [comment]
Rerunning the `/payload-job` above as it didn't pass the first time.

**Comment by DennisPeriquet** [comment]
definitely strange since the PR this is reverting introduced names like `openshift-csi-main-attacher-role`, `openshift-csi-main-provisioner-role`, and `openshift-csi-main-resizer-role` and they show up in the pathological test failure of the job run in `/payload-job`.

**Comment by neisw** [comment]
Looks like https://github.com/openshift/azure-disk-csi-driver-operator/pull/84/files is paired up with the changes we are trying to revert here and both will need to be reverted in tandem.

**Comment by dgoodwin** [comment]
Based on feedback from @jsafrane we believe it's best to revert all changes related to this jira that went into the affected payloads.


/label approved

**Comment by neisw** [comment]
Note the test failures for https://prow.ci.openshift.org/job-history/gs/origin-ci-test/logs/openshift-azure-file-csi-driver-operator-63-ci-4.14-upgrade-from-stable-4.13-e2e-azure-sdn-upgrade are related to the other revert for azure-disk-csi-driver-operator.  We likely need to override ci/prow/e2e-azure-file-csi 

`event happened 246 times, something is wrong: ns/openshift-cluster-csi-drivers deployment/azure-disk-csi-driver-operator hmsg/e18fd3d884 - pathological/true reason/ClusterRoleBindingUpdateFailed Failed to update ClusterRoleBinding.rbac.authorization.k8s.io/azure-disk-csi-attacher-binding: ClusterRoleBinding.rbac.authorization.k8s.io "azure-disk-csi-attacher-binding" is invalid: roleRef: Invalid value: rbac.RoleRef{APIGroup:"rbac.authorization.k8s.io", Kind:"ClusterRole", Name:"openshift-csi-main-attacher-role"}: cannot change roleRef From: 02:06:41Z To: 02:06:42Z result=reject `

**Pull request merged**
