### PR TITLE
OCPBUGS-28230: enforce termination message policy on all platform pods

### PR DESCRIPTION
**Pull request by deads2k**
found in https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-openshift-release-master-ci-4.16-e2e-azure-ovn-techpreview-serial/1787828675337523200

### CODE REVIEW

**Comment by dobsonj** [comment]
@deads2k the errors in https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-openshift-release-master-ci-4.16-e2e-azure-ovn-techpreview-serial/1787828675337523200 should be fixed by https://github.com/openshift/cluster-storage-operator/pull/470 and you already added `terminationMessagePolicy` for azure-file-csi-driver operands in https://github.com/openshift/csi-operator/pull/214

On 4.16+ azure-file-csi-driver-operator is [built from openshift/csi-operator](https://github.com/openshift-eng/ocp-build-data/blob/fe89d99a243e08c332eb19b339ea53031fb23755/images/azure-file-csi-driver-operator.yml#L11) instead of openshift/azure-file-csi-driver-operator

**Comment by jsafrane** [comment]
oops, we forgot to mark this repo as obsolete. @dobsonj, can you please review https://github.com/openshift/azure-file-csi-driver-operator/pull/106 ?

**Comment by dobsonj** [comment]
> oops, we forgot to mark this repo as obsolete. @dobsonj, can you please review #106 ?

Ack, done. I guess we can close this PR.
/close

**Pull request closed without merging**
