### PR TITLE
STOR-947: support disabling default StorageClass via ClusterCSIDriver

### PR DESCRIPTION
**Pull request by dobsonj**
https://issues.redhat.com/browse/STOR-947
Marking this WIP until openshift/library-go#1441 merges.
/cc @openshift/storage

### CODE REVIEW

**Comment by dobsonj** [comment]
This failure is real (caused by bumping library-go):
```
level=error msg=Cluster operator storage Degraded is True with AzureFileCSIDriverOperatorCR_AzureFileDriverStaticResourcesController_SyncError: AzureFileCSIDriverOperatorCRDegraded: AzureFileDriverStaticResourcesControllerDegraded: "csidriver.yaml" (string): CSIDriver file.csi.azure.com supports Ephemeral volume lifecycle but is missing required label security.openshift.io/csi-ephemeral-volume-profile
```
Apparently the [driver allows ephemeral](https://github.com/openshift/azure-file-csi-driver-operator/blob/6a0e02825222ac482db783f7672ce2aa6a6c8b4b/assets/csidriver.yaml#L14) (inline) volumes and we need to set the `security.openshift.io/csi-ephemeral-volume-profile` label.

**Comment by dobsonj** [comment]
Note to self: review the [driver parameters](https://github.com/openshift/azure-file-csi-driver/blob/85a79c417b330d75e79a59c2833f0b87de98c2ce/pkg/azurefile/controllerserver.go#L122-L215) and discuss with the team what would be an appropriate value for the label (i.e. restricted or privileged).

**Comment by dobsonj** [comment]
> Note to self: review the [driver parameters](https://github.com/openshift/azure-file-csi-driver/blob/85a79c417b330d75e79a59c2833f0b87de98c2ce/pkg/azurefile/controllerserver.go#L122-L215) and discuss with the team what would be an appropriate value for the label (i.e. restricted or privileged).

We agreed that it should be privileged by default (added [here](https://github.com/openshift/azure-file-csi-driver-operator/pull/42/commits/af87d724652779f125051dfdb2ff862b77eb172f)) but that we should allow the admin to change the value (added [here](https://github.com/openshift/library-go/pull/1441/commits/60a29fe3b7ad52a79886b7bfa3912f575d9f44f9)). This means we use a secure default but allow the admin to specify a more permissive policy if their use case requires it.

**Comment by dobsonj** [comment]
Basic functional test:
```
# Azure File

## patch SC, should get reverted by default
$ oc get sc
NAME                    PROVISIONER          RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
azurefile-csi           file.csi.azure.com   Delete          Immediate              true                   84m
managed-csi (default)   disk.csi.azure.com   Delete          WaitForFirstConsumer   true                   84m
$ oc patch sc azurefile-csi -p '{"allowVolumeExpansion":false}'
storageclass.storage.k8s.io/azurefile-csi patched
$ oc get sc azurefile-csi -o yaml | grep allowVolumeExpansion
allowVolumeExpansion: true

## Unmanaged: SC changes should persist
$ oc get clustercsidriver
NAME                 AGE
disk.csi.azure.com   85m
file.csi.azure.com   85m
$ oc edit clustercsidriver file.csi.azure.com
#  storageClassState: Unmanaged
clustercsidriver.operator.openshift.io/file.csi.azure.com edited
$ oc patch sc azurefile-csi -p '{"allowVolumeExpansion":false}'
storageclass.storage.k8s.io/azurefile-csi patched
$ oc get sc azurefile-csi -o yaml | grep allowVolumeExpansion
allowVolumeExpansion: false

## Removed: SC should be removed
$ oc edit clustercsidriver file.csi.azure.com
#  storageClassState: Removed
clustercsidriver.operator.openshift.io/file.csi.azure.com edited
$ oc get sc
NAME                    PROVISIONER          RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
managed-csi (default)   disk.csi.azure.com   Delete          WaitForFirstConsumer   true                   88m

## Managed: SC should be recreated. Changes should be reverted.
$ oc edit clustercsidriver file.csi.azure.com
#  storageClassState: Managed
clustercsidriver.operator.openshift.io/file.csi.azure.com edited
$ oc get sc
NAME                    PROVISIONER          RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
azurefile-csi           file.csi.azure.com   Delete          Immediate              true                   42s
managed-csi (default)   disk.csi.azure.com   Delete          WaitForFirstConsumer   true                   89m
$ oc patch sc azurefile-csi -p '{"allowVolumeExpansion":false}'
storageclass.storage.k8s.io/azurefile-csi patched
$ oc get sc azurefile-csi -o yaml | grep allowVolumeExpansion
allowVolumeExpansion: true

## Change csi-ephemeral-volume-profile label on CSIDriver (change should persist)
$ oc get csidriver file.csi.azure.com -o yaml
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  annotations:
    csi.openshift.io/managed: "true"
    operator.openshift.io/spec-hash: 9d1932775c60df2433bdcb362d11478167064398d9dbdade8579dbde4be91949
  creationTimestamp: "2023-01-05T20:38:36Z"
  labels:
    security.openshift.io/csi-ephemeral-volume-profile: privileged
  name: file.csi.azure.com
  resourceVersion: "5976"
  uid: 6c5e65dc-4a57-4e7f-9473-daaea3ca285b
spec:
  attachRequired: false
  fsGroupPolicy: None
  podInfoOnMount: true
  requiresRepublish: false
  storageCapacity: false
  volumeLifecycleModes:
  - Persistent
  - Ephemeral
$ oc label --overwrite csidriver file.csi.azure.com security.openshift.io/csi-ephemeral-volume-profile=restricted
csidriver.storage.k8s.io/file.csi.azure.com labeled
$ oc get csidriver file.csi.azure.com -o yaml | grep csi-ephemeral-volume-profile
    security.openshift.io/csi-ephemeral-volume-profile: restricted

## Remove csi-ephemeral-volume-profile label on CSIDriver (should be added back)
$ oc label csidriver file.csi.azure.com security.openshift.io/csi-ephemeral-volume-profile-
csidriver.storage.k8s.io/file.csi.azure.com unlabeled
$ oc get csidriver file.csi.azure.com -o yaml | grep csi-ephemeral-volume-profile
    security.openshift.io/csi-ephemeral-volume-profile: privileged
```

**Comment by dobsonj** [comment]
/retitle STOR-947: support disabling default StorageClass via ClusterCSIDriver

**Comment by ropatil010** [comment]
Payload: 4.13.0-0.ci.test-2023-01-25-044031-ci-ln-8y8dp9t-latest 

Pending test on csi-ephemeral-volume-profile label  

Test Results: 
###################test0_Default started #################
oc get clustercsidriver file.csi.azure.com -o yaml | grep 'storageClassState'

oc get sc
NAME                    PROVISIONER          RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
azurefile-csi                   file.csi.azure.com     Delete           Immediate                       true                   13m
managed-csi (default)   disk.csi.azure.com   Delete          WaitForFirstConsumer   true                   6m9s

 change managed-csi volumeBindingMode
 change managed-csi reclaimPolicy
 change azurefile-csi volumeBindingMode
 change azurefile-csi reclaimPolicy

 Bydefault test change managed-csi allowVolumeExpansion to false
storageclass.storage.k8s.io/managed-csi patched
 Bydefault result oc get sc managed-csi
NAME                    PROVISIONER          RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
managed-csi (default)   disk.csi.azure.com   Delete          WaitForFirstConsumer   true                   6m46s

 Bydefault test change azurefile-csi allowVolumeExpansion to false
storageclass.storage.k8s.io/azurefile-csi patched
 Bydefault result oc get sc azurefile-csi
NAME            PROVISIONER          RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
azurefile-csi   file.csi.azure.com   Delete          Immediate           true                   13m

oc get sc
NAME                    PROVISIONER          RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
azurefile-csi           file.csi.azure.com   Delete          Immediate              true                   13m
managed-csi (default)   disk.csi.azure.com   Delete          WaitForFirstConsumer   true                   7m5s

oc delete sc
storageclass.storage.k8s.io "managed-csi" deleted
storageclass.storage.k8s.io "azurefile-csi" deleted

oc get sc
NAME                    PROVISIONER          RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
azurefile-csi                    file.csi.azure.com     Delete          Immediate                       true                   6s
managed-csi (default)   disk.csi.azure.com   Delete          WaitForFirstConsumer   true                   13s
###################test1_Removed started #################
oc get clustercsidriver file.csi.azure.com -o yaml | grep 'storageClassState' 
  storageClassState: Removed

 Removed test change azurefile-csi allowVolumeExpansion to false
 Removed test change managed-csi allowVolumeExpansion to false
storageclass.storage.k8s.io/managed-csi patched

 Removed result oc get sc
NAME                    PROVISIONER          RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
managed-csi (default)   disk.csi.azure.com   Delete          WaitForFirstConsumer   true                   2m44s
###################test2_Managed started #################
oc get clustercsidriver file.csi.azure.com -o yaml | grep 'storageClassState'
  storageClassState: Managed

oc get sc
NAME                    PROVISIONER          RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
azurefile-csi           file.csi.azure.com   Delete          Immediate              true                   82s
managed-csi (default)   disk.csi.azure.com   Delete          WaitForFirstConsumer   true                   5m13s

 change managed-csi volumeBindingMode
 change managed-csi reclaimPolicy
 change azurefile-csi volumeBindingMode
 change azurefile-csi reclaimPolicy

 Managed test change managed-csi allowVolumeExpansion to false
storageclass.storage.k8s.io/managed-csi patched
 Managed result oc get sc managed-csi
NAME                    PROVISIONER          RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
managed-csi (default)   disk.csi.azure.com   Delete          WaitForFirstConsumer   true                   5m48s

 Managed test change azurefile-csi allowVolumeExpansion to false
storageclass.storage.k8s.io/azurefile-csi patched
 Managed result oc get sc azurefile-csi
NAME            PROVISIONER          RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
azurefile-csi   file.csi.azure.com   Delete          Immediate           true                   2m10s

oc get sc
NAME                    PROVISIONER          RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
azurefile-csi                    file.csi.azure.com   Delete            Immediate                       true                   2m16s
managed-csi (default)   disk.csi.azure.com   Delete          WaitForFirstConsumer   true                   6m7s

oc delete sc
storageclass.storage.k8s.io "managed-csi" deleted
storageclass.storage.k8s.io "azurefile-csi" deleted

oc get sc
NAME                    PROVISIONER          RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
azurefile-csi                    file.csi.azure.com     Delete          Immediate                       true                   3s
managed-csi (default)   disk.csi.azure.com   Delete          WaitForFirstConsumer   true                   9s
###################test3_Unmanaged started #################
oc get clustercsidriver file.csi.azure.com -o yaml | grep 'storageClassState'
  storageClassState: Unmanaged

oc get sc
NAME                    PROVISIONER          RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
azurefile-csi           file.csi.azure.com   Delete          Immediate              true                   2m6s
managed-csi (default)   disk.csi.azure.com   Delete          WaitForFirstConsumer   true                   2m12s

 change managed-csi volumeBindingMode
 change managed-csi reclaimPolicy
 change azurefile-csi volumeBindingMode
 change azurefile-csi reclaimPolicy

 Unmanaged test change managed-csi allowVolumeExpansion to false
storageclass.storage.k8s.io/managed-csi patched
 Unmanaged result oc get sc managed-csi
NAME                    PROVISIONER          RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
managed-csi (default)   disk.csi.azure.com   Delete          WaitForFirstConsumer   true                   2m47s

 Unmanaged test change azurefile-csi allowVolumeExpansion to false
storageclass.storage.k8s.io/azurefile-csi patched
 Unmanaged result oc get sc azurefile-csi
NAME            PROVISIONER          RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
azurefile-csi   file.csi.azure.com   Delete          Immediate           false                  2m53s

oc get sc
NAME                    PROVISIONER          RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
azurefile-csi           file.csi.azure.com   Delete          Immediate              false                  3m
managed-csi (default)   disk.csi.azure.com   Delete          WaitForFirstConsumer   true                   3m6s

oc delete sc
storageclass.storage.k8s.io "managed-csi" deleted
storageclass.storage.k8s.io "azurefile-csi" deleted

oc get sc
NAME                    PROVISIONER          RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
managed-csi (default)   disk.csi.azure.com   Delete          WaitForFirstConsumer   true                   9s
###################test4a_Multiple default sc started #################
oc get clustercsidriver file.csi.azure.com -o yaml | grep 'storageClassState'
  storageClassState: Managed

oc get sc
NAME                    PROVISIONER          RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
azurefile-csi                    file.csi.azure.com     Delete          Immediate                       true                   2m2s
managed-csi (default)   disk.csi.azure.com   Delete          WaitForFirstConsumer   true                   5m56s
Creating sc
storageclass.storage.k8s.io/testsc created
Applying patch to sc testsc for changing to default
storageclass.storage.k8s.io/testsc patched

oc get sc
NAME                    PROVISIONER          RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
azurefile-csi                    file.csi.azure.com   Delete           Immediate                       true                   2m18s
managed-csi (default)   disk.csi.azure.com  Delete          WaitForFirstConsumer   true                   6m12s
testsc (default)               file.csi.azure.com   Delete           Immediate                       true                   13s
###################test4b_Removed started #################
oc get clustercsidriver file.csi.azure.com -o yaml | grep 'storageClassState'
  storageClassState: Removed

oc get sc and check azurefile-csi should not be there, managed-csi and testsc should be there
NAME                    PROVISIONER          RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
managed-csi (default)   disk.csi.azure.com   Delete          WaitForFirstConsumer   true                   7m6s
testsc (default)               file.csi.azure.com     Delete          Immediate                       true                   67s
###################test4c_Managed sc started #################
oc get clustercsidriver file.csi.azure.com -o yaml | grep 'storageClassState'
  storageClassState: Managed

oc get sc all should be present now managed-csi, azurefile-csi, testsc
NAME                    PROVISIONER          RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
azurefile-csi                    file.csi.azure.com   Delete          Immediate                        true                   20s
managed-csi (default)   disk.csi.azure.com   Delete         WaitForFirstConsumer   true                   8m47s
testsc (default)               file.csi.azure.com   Delete          Immediate                        true                   2m48s
Deleting all sc
storageclass.storage.k8s.io "testsc" deleted
storageclass.storage.k8s.io "managed-csi" deleted
storageclass.storage.k8s.io "azurefile-csi" deleted

oc get sc azurefile-csi and managed-csi should be back to default
NAME                    PROVISIONER          RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
azurefile-csi                   file.csi.azure.com      Delete          Immediate                      true                   7s
managed-csi (default)   disk.csi.azure.com   Delete          WaitForFirstConsumer   true                   13s
###################test5a_Managed default sc started #################
oc get clustercsidriver file.csi.azure.com -o yaml | grep 'storageClassState'
  storageClassState: Managed

oc get sc
NAME                    PROVISIONER          RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
azurefile-csi                    file.csi.azure.com   Delete            Immediate                       true                   2m41s
managed-csi (default)   disk.csi.azure.com   Delete          WaitForFirstConsumer   true                   2m47s
###################test5b_Unmanaged default sc started #################
oc get clustercsidriver file.csi.azure.com -o yaml | grep 'storageClassState'
  storageClassState: Unmanaged

oc get sc
NAME                    PROVISIONER          RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
azurefile-csi                    file.csi.azure.com   Delete            Immediate                      true                   3m55s
managed-csi (default)   disk.csi.azure.com   Delete          WaitForFirstConsumer   true                   4m1s
Creating sc
storageclass.storage.k8s.io/testsc created
Applying patch to sc testsc for changing to default
storageclass.storage.k8s.io/testsc patched
Applying patch to sc managed-csi for changing to non default
storageclass.storage.k8s.io/managed-csi patched

oc get sc
NAME                    PROVISIONER          RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
azurefile-csi            file.csi.azure.com    Delete           Immediate                      true                   4m39s
managed-csi           disk.csi.azure.com   Delete          WaitForFirstConsumer   true                   4m45s
testsc (default)        file.csi.azure.com    Delete          Immediate                        true                   37s
###################test5c_Removed sc started #################
oc get clustercsidriver file.csi.azure.com -o yaml | grep 'storageClassState'
  storageClassState: Removed

oc get sc azurefile-csi should not be there, managed-csi, testsc should be there
NAME               PROVISIONER          RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
managed-csi        disk.csi.azure.com   Delete          WaitForFirstConsumer   true                   9m23s
testsc (default)     file.csi.azure.com   Delete             Immediate                     true                   5m15s
Deleting sc testsc
storageclass.storage.k8s.io "testsc" deleted
Deleting sc managed-csi
storageclass.storage.k8s.io "managed-csi" deleted

managed-csi should remain
NAME                    PROVISIONER          RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
managed-csi (default)   disk.csi.azure.com   Delete          WaitForFirstConsumer   true                   7s

**Comment by dobsonj** [comment]
> /docs-approved

/label docs-approved

**Comment by ropatil010** [comment]
Verified: 
Payload: 4.13.0-0.ci.test-2023-02-06-043724-ci-ln-b8ij3kt-latest 
Cluster bot: build openshift/azure-disk-csi-driver-operator#63,openshift/azure-file-csi-driver-operator#42  

rohitpatil@ropatil-mac Downloads % oc label --overwrite csidriver file.csi.azure.com security.openshift.io/csi-ephemeral-volume-profile=restricted
csidriver.storage.k8s.io/file.csi.azure.com labeled
rohitpatil@ropatil-mac Downloads % oc get csidriver file.csi.azure.com -o yaml | grep "security.openshift.io/csi-ephemeral-volume-profile"
    security.openshift.io/csi-ephemeral-volume-profile: restricted

rohitpatil@ropatil-mac Downloads % oc label --overwrite csidriver file.csi.azure.com security.openshift.io/csi-ephemeral-volume-profile=privileged
csidriver.storage.k8s.io/file.csi.azure.com labeled
rohitpatil@ropatil-mac Downloads % oc get csidriver file.csi.azure.com -o yaml | grep "security.openshift.io/csi-ephemeral-volume-profile"
    security.openshift.io/csi-ephemeral-volume-profile: privileged

May need bit additional validation codecheck/Optional. 
rohitpatil@ropatil-mac Downloads % oc label --overwrite csidriver file.csi.azure.com security.openshift.io/csi-ephemeral-volume-profile=restricted123
csidriver.storage.k8s.io/file.csi.azure.com labeled
rohitpatil@ropatil-mac Downloads % oc get csidriver file.csi.azure.com -o yaml | grep "security.openshift.io/csi-ephemeral-volume-profile"
    security.openshift.io/csi-ephemeral-volume-profile: restricted123

rohitpatil@ropatil-mac Downloads % oc label --overwrite csidriver file.csi.azure.com security.openshift.io/csi-ephemeral-volume-profile=abcd     
csidriver.storage.k8s.io/file.csi.azure.com labeled
rohitpatil@ropatil-mac Downloads % oc get csidriver file.csi.azure.com -o yaml | grep "security.openshift.io/csi-ephemeral-volume-profile"
    security.openshift.io/csi-ephemeral-volume-profile: abcd
    
/label qe-approved

**Comment by dobsonj** [comment]
ETRYAGAIN? `The provided client secret keys for app '4f03bcab-7b63-4617-9641-0e2eeb9cc5eb' are expired.`
/retest-required

**Pull request merged**
